### ISSUE TITLE
play.etcd.io down / non-functional

### ISSUE THREAD

**Issue by frittentheke** [etcd-io/etcdlabs#293]
Currently http://play.etcd.io/ seems to not work properly and only shows "Loading ..." on a white background.
Looking at the dev console indicates that the download of `http://play.etcd.io/main.2cfd0425a6b5577c52b2.bundle.js` is the issue here as this results in an incomplete file.

I also verified the issue with curl:

```
#curl -v -o /dev/null -L http://play.etcd.io/main.2cfd0425a6b5577c52b2.bundle.js


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host play.etcd.io:80 was resolved.
* IPv6: (none)
* IPv4: 35.230.70.199
*   Trying 35.230.70.199:80...
* Connected to play.etcd.io (35.230.70.199) port 80
* using HTTP/1.x
> GET /main.2cfd0425a6b5577c52b2.bundle.js HTTP/1.1
> Host: play.etcd.io
> User-Agent: curl/8.10.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< Server: nginx/1.12.1 (Ubuntu)
< Date: Tue, 08 Oct 2024 06:29:14 GMT
< Content-Type: application/javascript; charset=UTF-8
< Content-Length: 1361513
< Connection: keep-alive
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Accept-Ranges: bytes
< ETag: W/"14c669-lim2O1PKL4S13kIK/yglZ3etnKQ"
< Vary: Accept-Encoding
< 
{ [10929 bytes data]
  4 1329k    4 65841    0     0  38506      0  0:00:35  0:00:01  0:00:34 38503* end of response with 1260472 bytes missing
  7 1329k    7   98k    0     0  49954      0  0:00:27  0:00:02  0:00:25 49970
* closing connection #0
curl: (18) end of response with 1260472 bytes missing

```

**Comment by ivanvc** [comment]
I also noticed this while working on etcd-io/etcd#18649. I tried multiple browsers, and the page is stuck on "Loading...".

I'm a bit unfamiliar with this repository. By peeking at the `OWNERS` file, I see you're among the maintainers, @ahrtr and @jmhbnz. Who should take a look at this issue?

**Comment by jberkus** [comment]
Looks like this may be https-related.  I can make it work on Firefox for Linux, in http.

**Comment by jberkus** [comment]
Does anyone know where play.etcd.io actually runs?  Where is it hosted?

@serathius ?

**Comment by ahrtr** [comment]
> Does anyone know where play.etcd.io actually runs? Where is it hosted?

I guess only the previous maintainers know

**Comment by jberkus** [comment]
It's running on GCP somewhere.  NFI who owns the account.

We can always redirect the DNS, though.

**Comment by jmhbnz** [comment]
It runs in this compute instance in our `etcd-development` GCP project https://console.cloud.google.com/compute/instancesDetail/zones/us-west1-a/instances/play-etcd-io?project=etcd-development.

I'll try take a look at this but can't give any promises on timeframe.

**Comment by jmhbnz** [comment]
I've restarted the compute instance in GCP and it looks to be running again http://play.etcd.io/play

Just make sure to use `http` instead of `https` in browser.

Thanks for highlighting the issue @frittentheke
